config/routes.rb
Rails.application.routes.draw do
# I need to come back here and make sure this is correct

  resources :plants, except: [:show]
  get 'plant/:id', to: 'plants#show', as: 'plant_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def index
    @plants = Plant.all
  end

  def new
    @plant = Plant.new 
  end

  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plants_path, notice: 'Your plant has been created 🌱' }          
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    set_plant

    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plants_path, notice: 'Your plant has been updated 🌳' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    set_plant

    @plant.destroy
      respond_to do |format|
        format.html { redirect_to plants_path, notice: 'Your plant was successfully destroyed 💣' }
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:title, :lighting_preference, :main_image, :thumb_image)
  end

  def set_plant
    @plant = Plant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🌱 when to water 🌱</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<h2>🌱 This is where the nav partials and fancy SVGs and other things will go 🌱</h2>

<%= link_to 'Go to plants index 🌱', plants_path %>

app/views/plants/edit.html.erb
<h1>Tell me what's changed about your plant 🥦</h1>

<%= form_with model: @plant do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :lighting_preference %>
    <%= form.text_area :lighting_preference %>
  </div>

  <%= link_to 'Cancel', plants_path %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/index.html.erb
<h1>This is the Plant index page</h1>
<p>Find me in app/views/plants/index.html.erb</p>

<%= link_to 'Go home 🏡', root_path %>

<%= link_to 'Create a plant 🌱', new_plant_path %>

<% @plants.each do |plant| %>
    <h2>Plant name: <%= plant.title %></h2>

    <%= image_tag plant.thumb_image unless plant.thumb_image.nil? %>

    <p>Lighting preferences: <%= plant.lighting_preference %></p>
    <%= link_to "Edit", edit_plant_path(plant) %>
    <%= link_to "View plant", plant_show_path(plant) %>
    <%= link_to 'Delete this plant', plant_path(plant), method: :delete, data: { confirm: 'Are you sure you want to kill this plant? 🚩' } %>
<% end %>

app/views/plants/new.html.erb
<h1>Tell me about your new plant 🌱</h1>

<%= form_with model: @plant do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :lighting_preference %>
    <%= form.text_area :lighting_preference %>
  </div>

  <%= link_to 'Cancel', plants_path %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/show.html.erb
<h1><%= @plant.title %></h1>

<%= image_tag @plant.main_image %>
<p>Lighting preference: <%= @plant.lighting_preference %></p>

<%= link_to "Edit", edit_plant_path %>
<%= link_to "Back", plants_path %>